### ISSUE TITLE
Site no longer updating

### ISSUE THREAD

**Issue by ac1513** [Cloud-SPAN/02genomics#3]
Looks like something in 4d10cb3ef0836b6278a696f10148909db8e46c5f broke the page build. 

This is the error we're getting during the build with Jekyll 
```
Run actions/jekyll-build-pages@v[1](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:1)
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv104_03a212 --label 4cd[9](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:10)8f --workdir /github/workspace --rm -e INPUT_SOURCE -e INPUT_DESTINATION -e INPUT_FUTURE -e INPUT_BUILD_REVISION -e INPUT_VERBOSE -e INPUT_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e ACTIONS_ID_TOKEN_REQUEST_URL -e ACTIONS_ID_TOKEN_REQUEST_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/02genomics/02genomics":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.4
  Logging at level: debug
Configuration file: /github/workspace/./_config.yml
      GitHub Pages: github-pages v227
      GitHub Pages: jekyll v3.9.2
             Theme: jekyll-theme-primer
      Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0
         Requiring: jekyll-github-metadata
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': File exists @ dir_s_mkdir - /github/workspace/_site/CITATION.cff (Errno::EEXIST)
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/static_file.rb:[10](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:11)3:in `write'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:209:in `block in write'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:332:in `block (2 levels) in each_site_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:331:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:331:in `block in each_site_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:330:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:330:in `each_site_file'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:208:in `write'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:73:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-227/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: jekyll-remote-theme
   GitHub Metadata: Initializing...
            Source: /github/workspace/.
       Destination: /github/workspace/./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Theme: cloud-span/cloud-span-theme
      Theme source: /tmp/jekyll-remote-theme-20220804-8-1fqt6ds
      Remote Theme: Using theme cloud-span/cloud-span-theme
      Remote Theme: Downloading https://codeload.github.com/cloud-span/cloud-span-theme/zip/HEAD to /tmp/jekyll-remote-theme-20220804-8-16voz1z.zip
      Remote Theme: Unzipping /tmp/jekyll-remote-theme-20220804-8-16voz1z.zip to /tmp/jekyll-remote-theme-20220804-8-1fqt6ds
       EntryFilter: excluded /bin
       EntryFilter: excluded /Makefile
           Reading: _episodes/01-writing-scripts.md
           Reading: _episodes/03-background.md
           Reading: _episodes/02-organization.md
           Reading: _extras/guide.md
           Reading: _extras/about.md
        Generating: JekyllOptionalFrontMatter::Generator finished in 0.000306103 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 0.002839024 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 5.501e-06 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.0013099[11](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:12) seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.00078[15](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:16)06 seconds.
         Requiring: kramdown-parser-gfm
        Generating: JekyllTitlesFromHeadings::Generator finished in 0.01[16](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:17)94699 seconds.
         Rendering: _episodes/01-writing-scripts.md
  Pre-Render Hooks: _episodes/01-writing-scripts.md
  Rendering Markup: _episodes/01-writing-scripts.md
  Rendering Layout: _episodes/01-writing-scripts.md
     Layout source: theme
   GitHub Metadata: Generating for Cloud-SPAN/02genomics
   GitHub Metadata: Calling @client.pages("Cloud-SPAN/02genomics", {})
   GitHub Metadata: Calling @client.list_repos("Cloud-SPAN", {:type=>"public", :accept=>"application/vnd.github.mercy-preview+json"})
         Rendering: _episodes/02-organization.md
  Pre-Render Hooks: _episodes/02-organization.md
  Rendering Markup: _episodes/02-organization.md
  Rendering Layout: _episodes/02-organization.md
     Layout source: theme
         Rendering: _episodes/03-background.md
  Pre-Render Hooks: _episodes/03-background.md
  Rendering Markup: _episodes/03-background.md
  Rendering Layout: _episodes/03-background.md
     Layout source: theme
         Rendering: _extras/about.md
  Pre-Render Hooks: _extras/about.md
  Rendering Markup: _extras/about.md
  Rendering Layout: _extras/about.md
     Layout source: theme
         Rendering: _extras/guide.md
  Pre-Render Hooks: _extras/guide.md
  Rendering Markup: _extras/guide.md
  Rendering Layout: _extras/guide.md
     Layout source: theme
         Rendering: CODE_OF_CONDUCT.md
  Pre-Render Hooks: CODE_OF_CONDUCT.md
  Rendering Liquid: CODE_OF_CONDUCT.md
  Rendering Markup: CODE_OF_CONDUCT.md
  Rendering Layout: CODE_OF_CONDUCT.md
     Layout source: theme
         Rendering: LICENSE.md
  Pre-Render Hooks: LICENSE.md
  Rendering Liquid: LICENSE.md
  Rendering Markup: LICENSE.md
  Rendering Layout: LICENSE.md
     Layout source: theme
         Rendering: aio.md
  Pre-Render Hooks: aio.md
  Rendering Liquid: aio.md
  Rendering Markup: aio.md
  Rendering Layout: aio.md
     Layout source: theme
         Rendering: index.md
  Pre-Render Hooks: index.md
  Rendering Liquid: index.md
  Rendering Markup: index.md
  Rendering Layout: index.md
     Layout source: theme
         Rendering: reference.md
  Pre-Render Hooks: reference.md
  Rendering Markup: reference.md
  Rendering Layout: reference.md
     Layout source: theme
         Rendering: setup.md
  Pre-Render Hooks: setup.md
  Rendering Liquid: setup.md
  Rendering Markup: setup.md
  Rendering Layout: setup.md
     Layout source: theme
         Rendering: assets/css/lesson.scss
  Pre-Render Hooks: assets/css/lesson.scss
  Rendering Markup: assets/css/lesson.scss
           Writing: /github/workspace/_site/CODE_OF_CONDUCT.html
           Writing: /github/workspace/_site/LICENSE.html
           Writing: /github/workspace/_site/aio.html
           Writing: /github/workspace/_site/index.html
           Writing: /github/workspace/_site/reference.html
           Writing: /github/workspace/_site/setup.html
           Writing: /github/workspace/_site/assets/css/lesson.css
           Writing: /github/workspace/_site/01-writing-scripts/index.html
           Writing: /github/workspace/_site/02-organization/index.html
           Writing: /github/workspace/_site/03-background/index.html
github-pages 227 | Error:  File exists @ dir_s_mkdir - /github/workspace/_site/CITATION.cff
      Remote Theme: Cleaning up /tmp/jekyll-remote-theme-[20](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:21)[22](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:23)0[80](https://github.com/Cloud-SPAN/02genomics/runs/7668644263?check_suite_focus=true#step:4:81)4-8-1fqt6ds
```

**Comment by evelyngreeves** [comment]
Thanks for adding this Annabel! Looks like it's the commit where I added the .cff file, not sure why 🤔 I'll look into it now

**Comment by evelyngreeves** [comment]
@ac1513 I've reverted the commit and it seems to have fixed it - your edit has gone through now and is changed on the webpage:
![image](https://user-images.githubusercontent.com/89016177/182857522-2a956c28-7970-4b3e-a032-dcf1da3f1a35.png)

Now to work out why the .cff file was causing an issue in the first place...

**Comment by evelyngreeves** [comment]
All fixed, I think. I think I accidentally put the .cff file in the 'episodes' folder which was confusing Jekyll when it tried to build the site. It's moved to the main directory now and the citation looks to be working.

I'll close this issue! 💖

**Comment by ac1513** [comment]
Brilliant, thanks for working it out!

**Comment by 3mmaRand** [comment]
Thanks for fixing that @evelyngreeves
